### ISSUE TITLE
Commands[util_js_1.capitalize(...)] is not a constructor

### ISSUE THREAD

**Issue by KevinCepria** [soramitsu/iroha-helpers#27]
Running commands.substractAssetQuantity throws an error: 
```
ERROR TypeError: Commands[util_js_1.capitalize(...)] is not a constructor
at Object.addCommand (/home/kevin/work/proj/node_modules/iroha-helpers/lib/txHelper.js:41:26)
at Object.substractAssetQuantity (/home/kevin/work/proj/node_modules/iroha-helpers/lib/commands/index.js:216:58)
at Function.subtractAssetQuantity (/home/kevin/work/proj/providers/iroha/commands/AccountCommandsProvider.js:42:37)
at CashOutHandler.doTransaction (/home/kevin/work/proj/providers/handler/CashOutHandler.js:20:50)
```
Here is a sample code:

```
static async subtractAssetQuantity({privKeys, account, assetId, amount}, quorum = 1) {
    const command = commandService(privKeys, account, quorum)
    try {
      const result = await commands.substractAssetQuantity(
        command, { assetId, amount }
      )
      return result
    } finally {
      grpc.closeClient(command.commandService)
    }
  }

```
I have double checked all of my parameters and they have values.

**Comment by Pobepto** [comment]
@KevinCepria, Hi! Thank you for your bug report! I found a typo in library. I will try to release new version soon.

**Comment by KevinCepria** [comment]
@Pobepto Hello thank you for responding. Can you pinpoint where to the typo is and how to correct it? My team currently has a fork and need this to be fixed immediately.

**Comment by djose1512** [comment]
Hello, is there a solution?

**Comment by Pobepto** [comment]
Yes, as I remember this issue was fixed. Open new topic if you have a problem.
